# Generated by Django 2.2.12 on 2022-04-13 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_CIF', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('cliente_nombreEmpresa', models.CharField(max_length=45)),
                ('cliente_direccion', models.CharField(max_length=11)),
                ('clientw_datosContacto', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Componente',
            fields=[
                ('componente_referencia', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('componente_nombre', models.CharField(max_length=45)),
                ('componente_marca', models.CharField(max_length=45)),
                ('componente_imagen', models.ImageField(blank=True, upload_to='deustronic/static/img/componentes', verbose_name='componente_imagen')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('producto_referencia', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('producto_nombre', models.CharField(max_length=45)),
                ('producto_categoria', models.CharField(max_length=25)),
                ('producto_descripcion', models.CharField(max_length=255)),
                ('producto_precio', models.FloatField()),
                ('producto_imagen', models.ImageField(blank=True, null=True, upload_to='deustronic/static/img/productos', verbose_name='producto_imagen')),
                ('producto_componente', models.ManyToManyField(null=True, to='deustronic.Componente')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('pedido_referencia', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('pedido_fecha', models.DateField(auto_now=True)),
                ('pedido_cantidadproducto', models.IntegerField()),
                ('pedido_precioTotal', models.FloatField()),
                ('pedido_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deustronic.Cliente')),
                ('pedido_producto', models.ManyToManyField(to='deustronic.Producto')),
            ],
        ),
    ]
