# Generated by Django 2.2.12 on 2022-04-13 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deustronic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='producto_componente',
            field=models.ManyToManyField(to='deustronic.Componente'),
        ),
    ]
