# Generated by Django 4.0.4 on 2022-05-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deustronic', '0003_auto_20220425_1552'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_CIF',
            new_name='CIF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_datosContacto',
            new_name='datosContacto',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_direccion',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='cliente_nombreEmpresa',
            new_name='nombreEmpresa',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='componente_marca',
            new_name='marca',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='componente_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='componente',
            old_name='componente_referencia',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_cantidadproducto',
            new_name='cantidadproducto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_cliente',
            new_name='cliente',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_fecha',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_precioTotal',
            new_name='precioTotal',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_producto',
            new_name='producto',
        ),
        migrations.RenameField(
            model_name='pedido',
            old_name='pedido_referencia',
            new_name='referencia',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_categoria',
            new_name='categoria',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_componente',
            new_name='componente',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_descripcion',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_nombre',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_precio',
            new_name='precio',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='producto_referencia',
            new_name='referencia',
        ),
        migrations.RemoveField(
            model_name='componente',
            name='componente_imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='producto_imagen',
        ),
        migrations.AddField(
            model_name='componente',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='deustronic/static/img/componentes', verbose_name='imagen'),
        ),
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='deustronic/static/img/productos', verbose_name='imagen'),
        ),
    ]
