# Generated by Django 4.0.4 on 2022-05-02 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deustronic', '0004_rename_cliente_cif_cliente_cif_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='CIF',
            field=models.IntegerField(max_length=9, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='componente',
            name='referencia',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='referencia',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='referencia',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
